export const MAIN_SCREEN = 'MAIN_SCREEN';
export const SOURCE_NEWS_SCREEN = 'SOURCE_NEWS_SCREEN';
export const MY_WEBVIEW = 'MY_WEBVIEW';
export const PREFRENCES_SCREEN = 'PREFRENCES_SCREEN';
export const SEARCH_SCREEN = 'SEARCH_SCREEN';
